### ISSUE TITLE
503 Service Temporarily Unavailable when using Fargate

### ISSUE THREAD

**Issue by chrisbull** [prisma/prisma-templates#28]
So I keep following all the instructions [here](https://www.prisma.io/docs/tutorials/deploy-prisma-servers/aws-fargate-joofei3ahd) ... it gets created successfully, but whenever I access the externalUrl I get a 503 service temp unavail error. 

I'm using an already existing Postgres database hosted on AWS, instead of using the templates. The logs show a connection error with the db. Is there a reason you guys haven't created a `aws/postgres.yml` version yet? I'm not too familiar with Fargate (yet), so any help with how to connect Prisma to my existing db while using Fargate would be very appreciated.

Thanks in advance for the help!

Btw - would be really great if you guys (the Prisma team) could create a more simple way to deploy Prisma Server on AWS. Maybe could add something to the cli?

**Comment by dan003400** [comment]
I am having this same issue with MongoDB, we are using Atlas to host our MongoDB clusters. Any support here @prisma???

**Comment by haruska** [comment]
Couple of things that have killed my day but hopefully will help someone else that comes across this:

1) You need to set the SSL flag to true. This isn't in the database connector for some reason, but the top level prisma config... jesus. It's a postgres specific flag. anyway. I also added the connectionLimit but i'm guessing that's optional?

```
          Environment:
            - Name: PRISMA_CONFIG
              Value: !Sub 
                - |
                  port: 60000
                  managementApiSecret: ${ManagementApiSecret}
                  databases:
                    default:
                      connector: ${DbConnector}
                      host: ${DbHost}
                      port: ${DbPort}
                      user: ${DbUser}
                      password: ${DbPassword}
                      connectionLimit: ${DbConnectionLimit}
                      migrations: true
                      ssl: true
                  ssl: true
```

2) This template sets up a non-SSL public endpoint to your prisma server. I would convert that to SSL. It involves having a cert and a CNAME but you should certainly protect the traffic on the public net side of things.
